---
- name: K10 Deploy
  hosts: localhost
  vars_files:
    - vars/vault_vars.yaml
  vars:
    helm_chart_url: "https://charts.kasten.io/"
  collections:
    - kubernetes.core
  tasks:
# Creating the namespace in the kubernete cluster
    - name: Create Kasten K10 namespace
      k8s:
        name: kasten-io # defining the namespace
        api_version: v1
        kind: Namespace
        state: present
        
# Adding Helm repository for Kasten K10
    - name: Add Kasten helm repo
      kubernetes.core.helm_repository:
        name: kasten
        state: present
        repo_url: '{{ helm_chart_url }}'
      register: helmrepo

# Installing Kasten K10 for AzureAWS AKS
    - name: Install Kasten K10 chart
      kubernetes.core.helm:
        name: k10
        namespace: kasten-io
        chart_ref: kasten/k10
        wait: True
        state: present
        values:
            secrets:
                azureClientId: "{{ azureclientID }}"
            externalGateway:
                create: true
            auth:
                basicAuth:
                    enabled: true
                    htpasswd: "{{ LOGIN }}"

#  Accept EULA
    - name: Accept Kasten EULA
      k8s:
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: k10-eula-info
            namespace: kasten-io
          data:
            accepted: "true"
            company: '{{ company }}'
            email: '{{ email }}'

# Creating an Location Profile Secret
    - name: CREATE AZURE STORAGE ACCOUNT SECRET
      kubernetes.core.k8s:
        state: present
        definition: 
          apiVersion: v1
          kind: Secret
          type: secrets.kanister.io/azure             
          metadata:
            name: "k10-azblob-{{ bucket_name }}-secret"
            namespace: kasten-io     
          data:
            azure_storage_account_id: "{{ bucket_name|b64encode }}"
            azure_storage_environment: "{{ azure_storage_env|b64encode }}"
            azure_storage_key: "{{ azure_storage_key|b64encode }}"


# Creating an Location Profile
    - name: Creating an Location Profile with DR Data
      kubernetes.core.k8s:
        state: present
        definition: 
            apiVersion: config.kio.kasten.io/v1alpha1
            kind: Profile
            metadata:
              name: "profile-azblob-{{ bucket_name }}"
              namespace: kasten-io
            spec:
              type: Location
              locationSpec:
                credential:
                  secretType: AzStorageAccount
                  secret:
                    apiVersion: v1
                    kind: Secret
                    name: "k10-azblob-{{ bucket_name }}-secret"
                    namespace: kasten-io
                type: ObjectStore
                objectStore:
                  name: "{{ bucket_name }}"
                  objectStoreType: AZ

# Create Policy presets
    - name: Create Policy Presets from Files
      kubernetes.core.k8s:
        definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
      with_fileglob:
          - "policypresets/*.yaml"

# Create Backup Policy for Cluster-wide resources
    - name: "Create policy for cluster-wide resources"
      kubernetes.core.k8s:
        state: present
        definition:
            apiVersion: config.kio.kasten.io/v1alpha1
            kind: Policy
            metadata:
              name: cluster-backup
              namespace: kasten-io
            spec:
              comment: Backup Policy
              presetRef:
                name: silver-policy-preset
                namespace: kasten-io
              actions:
              - action: backup
              selector:
                matchExpressions:
                - key: k10.kasten.io/appNamespace
                  operator: In
                  values:
                  - kasten-io-cluster                

#Create TransformSet
    - name: "Create sample TransformSet"
      kubernetes.core.k8s:
        state: present
        definition:
            kind: TransformSet
            apiVersion: config.kio.kasten.io/v1alpha1
            metadata:
              name: dr-transforms
              namespace: kasten-io
            spec:
              comment: |
                Modify the storageClass to change storage tier.
              transforms:
                - subject:
                    resource: persistentvolumeclaims
                  name: ChangeStorageClass
                  json:
                    - op: replace
                      path: /spec/storageClassName
                      value: standard-csi
                - subject:
                    resource: deployments
                  name: ScaleDeployment
                  json:
                    - op: replace
                      path: /spec/replicas
                      value: 1                      

#Create BluePrint App Consistent Backups
    - name: Create Kanister Blueprint for MongoDB Statefulset
      kubernetes.core.k8s:
        state: present
        src: blueprints/bp-mongodb-lock.yaml        

    - name: Create Kanister Blueprint for PostgreSQL Statefulset
      kubernetes.core.k8s:
        state: present
        src: blueprints/bp-postgresql-dump.yaml

    - name: Create Kanister Blueprint for MariaDB Statefulset
      kubernetes.core.k8s:
        state: present
        src: blueprints/bp-mariadb-dump.yaml

    - name: Create Kanister Blueprint for MySQL Lock
      kubernetes.core.k8s:
        state: present
        src: blueprints/bp-mysql-lock.yaml

    - name: Create Kanister Blueprint for MySQL Dump
      kubernetes.core.k8s:
        state: present
        src: blueprints/bp-mysql-dump.yaml

    - name: Create Kanister Blueprint for ElasticSearch Dump
      kubernetes.core.k8s:
        state: present
        src: blueprints/bp-elasticsearch-dump.yaml        

#Create BluePrintBinding
    - name: "Create BluePrintBinding for ElasticSearch Consistent Backup - statefulset"
      kubernetes.core.k8s:
        state: present
        definition:
            apiVersion: config.kio.kasten.io/v1alpha1
            kind: BlueprintBinding
            metadata:
              name: bpb-elasticsearch-dump
              namespace: kasten-io
            spec:
              blueprintRef:
                name: bp-elasticsearch-dump
                namespace: kasten-io
              resources:
                matchAll:
                  - type:
                      operator: In
                      values:
                        - group: apps
                          resource: statefulsets
                  - annotations:
                      key: kanister.kasten.io/blueprint
                      operator: DoesNotExist
                  - labels:
                      key: database-type
                      operator: In
                      values:
                        - "elasticsearch"

    - name: "Create BluePrintBinding for MariaDB Consistent Backup - statefulset"
      kubernetes.core.k8s:
        state: present
        definition:
            apiVersion: config.kio.kasten.io/v1alpha1
            kind: BlueprintBinding
            metadata:
              name: bpb-mariadb-dump
              namespace: kasten-io
            spec:
              blueprintRef:
                name: bp-mariadb-dump
                namespace: kasten-io
              resources:
                matchAll:
                  - type:
                      operator: In
                      values:
                        - group: apps
                          resource: statefulsets
                  - annotations:
                      key: kanister.kasten.io/blueprint
                      operator: DoesNotExist
                  - labels:
                      key: database-type
                      operator: In
                      values:
                        - "mariadb"
 
    - name: "Create BluePrintBinding for MongoDB Consistent Backup - statefulset"
      kubernetes.core.k8s:
        state: present
        definition:
            apiVersion: config.kio.kasten.io/v1alpha1
            kind: BlueprintBinding
            metadata:
              name: bpb-mongodb-lock
              namespace: kasten-io
            spec:
              blueprintRef:
                name: bp-mongodb-lock
                namespace: kasten-io
              resources:
                matchAll:
                  - type:
                      operator: In
                      values:
                        - group: apps
                          resource: statefulsets
                  - annotations:
                      key: kanister.kasten.io/blueprint
                      operator: DoesNotExist
                  - labels:
                      key: database-type
                      operator: In
                      values:
                        - "mongodb"
         
    - name: "Create BluePrintBinding for PostgreSQL Consistent Backup - statefulset"
      kubernetes.core.k8s:
        state: present
        definition:
            apiVersion: config.kio.kasten.io/v1alpha1
            kind: BlueprintBinding
            metadata:
              name: bpb-postgresql-dump
              namespace: kasten-io
            spec:
              blueprintRef:
                name: bp-postgresql-dump
                namespace: kasten-io
              resources:
                matchAll:
                  - type:
                      operator: In
                      values:
                        - group: apps
                          resource: statefulsets
                  - annotations:
                      key: kanister.kasten.io/blueprint
                      operator: DoesNotExist
                  - labels:
                      key: database-type
                      operator: In
                      values:
                        - "postgresql"

    - name: "Create BluePrintBinding for MySQL Lock - statefulset"
      kubernetes.core.k8s:
        state: present
        definition:
            apiVersion: config.kio.kasten.io/v1alpha1
            kind: BlueprintBinding
            metadata:
              name: bpb-mysql-lock
              namespace: kasten-io
            spec:
              blueprintRef:
                name: bp-mysql-lock
                namespace: kasten-io
              resources:
                matchAll:
                  - type:
                      operator: In
                      values:
                        - group: apps
                          resource: statefulsets
                  - annotations:
                      key: kanister.kasten.io/blueprint
                      operator: DoesNotExist
                  - labels:
                      key: database-type
                      operator: In
                      values:
                        - "mysql-lock"

    - name: "Create BluePrintBinding for MySQL Dump - statefulset"
      kubernetes.core.k8s:
        state: present
        definition:
            apiVersion: config.kio.kasten.io/v1alpha1
            kind: BlueprintBinding
            metadata:
              name: bpb-mysql-dump
              namespace: kasten-io
            spec:
              blueprintRef:
                name: bp-mysql-dump
                namespace: kasten-io
              resources:
                matchAll:
                  - type:
                      operator: In
                      values:
                        - group: apps
                          resource: statefulsets
                  - annotations:
                      key: kanister.kasten.io/blueprint
                      operator: DoesNotExist
                  - labels:
                      key: database-type
                      operator: In
                      values:
                        - "mysql-dump"