apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: mongo-hooks
  namespace: kasten-io
actions:
  backupPosthook:
    name: ""
    kind: ""
    phases:
      - func: KubeExec
        name: unlockMongo
        args:
          command:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              mongo --authenticationDatabase admin --eval="db.fsyncUnlock()"
          namespace: "{{ .Deployment.Namespace }}"
          pod: "{{ index .Deployment.Pods 0 }}"
  backupPrehook:
    name: ""
    kind: ""
    phases:
      - func: KubeExec
        name: lockMongo
        args:
          command:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              mongo --authenticationDatabase admin --eval="db.fsyncLock()"
          namespace: "{{ .Deployment.Namespace }}"
          pod: "{{ index .Deployment.Pods 0 }}"